#include<stdio.h>
#include<string.h>

int main(){
    char nama[100][50] = {
        "ABRAHAM MAHAYANA SETIAWAN",
        "ALEXANDER IMMANUEL SAMOSIR",
        "ANDREAS LIUJAYA WIRANATA",
        "CAROLINE NATALIA AMRAN",
        "CATHERINE OLIVIA WINANDA",
        "DAVIN RAFFILIO",
        "DEXTER VALERIAN KRISNADHI",
        "DIANDRA PRAMESTI KINASIH",
        "EVOTIANUS",
        "FELIX GUSTINO TJUATJA",
        "FREDY SUNJAYA",
        "GRACE ADELINE KHARISMA",
        "GRISELLA MEIRISIA ZEGA",
        "HOSANNIA MICHAELA MARSINTA HARDIPUTRI",
        "HOWAN ANDERSON",
        "IGNES ANGELICA",
        "MICHAEL",
        "MUHAMMAD ARYA AQILAH FAUZAN",
        "PETER PRATAMA MULYADI",
        "RICHIE HARTONO",
        "SUPANDI SAPUTRA",
        "VALINA EVELYN PRANOTO",
        "VANECHKA RADJA WINATA",
        "AGNES RINAWATI NAULITA SIANTURI",
        "KEREN HOSANNA BIRILA",
        "STEPHANIE ANASTASIA MAKMUR",
        "NEISYA HOLLY SANTOSO",
        "NATHASYA RIZANDI",
        "ARI KUSUMADEWI",
        "JOELIARDO GERALD LEVIOTHNIEL",
        "SHAQUILLE DITAMA PUTRA",
        "MICHAEL SCUDERIA TANUDJAJA",
        "ARIYA GUNANANDA",
        "MATTHEW ALBERT SETIAWAN",
        "PUTU ARYASATYA DHARMA KENZHIE",
    };
    return 0;
}